/* ===========================================================================
 * The deliverable icons as particles: decoding and drawing.
 * ---------------------------------------------------------------------------
 * The dots come from content/glyph-dots.ts (generated by
 * scripts/glyph-dots.mjs, which documents the format and the treatment).
 * Each icon is a set of dots on a grid; this draws one frame of them.
 *
 * The client, 2026-10-09, chose three behaviours from a prototype, to echo
 * the particles across the site (the hero re-forms the same particles from
 * one shape into the next):
 *
 *   assemble  the dots fly in from a scattered cloud, curving, staggered,
 *             and settle into the drawing, the first time it is shown;
 *   light     the depth light follows the pointer, and the dots near it
 *             swell, brighten and part around it;
 *   drift     the scatter around each drawing drifts and twinkles, and the
 *             drawing shimmers faintly.
 *
 * Depth (the "B2" treatment): every icon is lit from one direction. Dots on
 * the lit side keep their size and the far side shrinks to 60%. By default
 * the light is at the top left; under "light" it turns toward the pointer.
 *
 * drawDots is a pure function of its inputs (no clock, no DOM), so a frame
 * can be drawn deliberately and measured.
 * ======================================================================== */

export const PITCH = 2.9;
const B32 = "0123456789abcdefghijklmnopqrstuv";
/** Sizes 0-3: the drawing's dots, in four steps. 4-7: the scatter. */
const SIZES = [0.2, 0.31, 0.41, 0.5, 0.1, 0.13, 0.15, 0.18].map((s) => s * PITCH);
/** Light, violet, sky; the scatter is a quieter slate. */
const COLOURS: [number, number, number][] = [[226, 232, 240], [167, 139, 250], [56, 189, 248]];
const SCATTER: [number, number, number] = [203, 213, 225];

export type Dot = {
  x: number; y: number; r: number; rgb: [number, number, number]; halo: boolean;
  /** Per-dot randomness: where it assembles from, its curve, its phase. */
  ang: number; rad: number; ph: number; lag: number; swirl: number;
};

const hash = (a: number, b: number) => { const v = Math.sin(a * 127.1 + b * 311.7) * 43758.5453; return v - Math.floor(v); };

export function decodeDots(code: string, seed = 1): Dot[] {
  const [head, body = ""] = code.split(":");
  const [ox, oy] = head.split(",").map(Number);
  const out: Dot[] = [];
  for (let k = 0; k + 2 < body.length; k += 3) {
    const i = B32.indexOf(body[k]), j = B32.indexOf(body[k + 1]), v = B32.indexOf(body[k + 2]);
    if (i < 0 || j < 0 || v < 0) break;
    const size = Math.floor(v / 3), halo = size >= 4;
    const h1 = hash(k, seed), h2 = hash(k + 7, seed * 3.1);
    out.push({
      x: ox + i * PITCH, y: oy + j * PITCH, r: SIZES[size], rgb: halo ? SCATTER : COLOURS[v % 3], halo,
      ang: h1 * Math.PI * 2, rad: 16 + 22 * h2, ph: h2 * 6.283, lag: h1 * 0.35, swirl: (h2 - 0.5) * 14,
    });
  }
  return out;
}

/** The light the icons are lit from at rest: the top left. */
export const DEFAULT_LIGHT: [number, number] = [-0.78, -0.62];
/** How long one dot takes to arrive, and the latest a dot starts. */
export const ASSEMBLE_S = 1.05, ASSEMBLE_LAG_S = 0.35;

export type Frame = {
  /** Seconds since this icon began assembling; null when it is simply shown. */
  assemble: number | null;
  /** Unit vector toward the light, in the drawing's own coordinates. */
  light: [number, number];
  /** The pointer in the drawing's coordinates (0-64, 0-48), with how present
   *  it is (0 to 1, eased), or null. */
  pointer: [number, number] | null;
  presence: number;
  /** Seconds, for the drift; null for none. */
  drift: number | null;
  /** Which dots: all, the drawing's own (cacheable), or only the scatter. */
  only?: "body" | "halo";
};

const clamp01 = (v: number) => Math.min(1, Math.max(0, v));
const lerp = (a: number, b: number, t: number) => a + (b - a) * t;

/** Draws one icon into ctx, which is already transformed so that the
 *  drawing's 64 x 48 box maps onto the icon's place on the page.
 *
 *  Dots are batched: one path per colour and opacity, filled once, rather
 *  than one fill per dot. Profiled on the home page (12 icons, ~130 dots
 *  each), filling dot by dot cost ~140 ms of main thread per second. */
export function drawDots(ctx: CanvasRenderingContext2D, dots: Dot[], f: Frame) {
  const [lx, ly] = f.light;
  const batches = new Map<string, Path2D>();
  for (const d of dots) {
    if (f.only && (f.only === "halo") !== d.halo) continue;
    let x = d.x, y = d.y, a = d.halo ? 0.8 : 1;
    let r = d.r * (1 - 0.4 * clamp01(0.5 - ((d.x - 32) * lx + (d.y - 24) * ly) / 64));
    let [cr, cg, cb] = d.rgb;

    if (f.assemble !== null) {
      const p = clamp01((f.assemble - d.lag) / ASSEMBLE_S);
      if (p <= 0) continue;
      if (p < 1) {
        const e = 1 - (1 - p) ** 3;
        const sx = 32 + Math.cos(d.ang) * d.rad * 1.4, sy = 24 + Math.sin(d.ang) * d.rad;
        const sw = Math.sin(e * Math.PI) * d.swirl;   // curve in, not a straight line
        x = lerp(sx, x, e) - sw * Math.sin(d.ang);
        y = lerp(sy, y, e) + sw * Math.cos(d.ang);
        r *= lerp(0.35, 1, e);
        a *= Math.min(1, p * 2.5);
      }
    }

    if (f.drift !== null) {
      const t = f.drift;
      if (d.halo) {
        x += Math.sin(t * 0.7 + d.ph) * 1.1;
        y += Math.cos(t * 0.55 + d.ph) * 1.1;
        a *= 0.45 + 0.55 * (0.5 + 0.5 * Math.sin(t * 1.4 + d.ph * 3));
      } else {
        r *= 1 + 0.1 * Math.sin(t * 1.8 - (d.x + d.y) * 0.11);
      }
    }

    if (f.pointer && f.presence > 0.001) {
      const dx = x - f.pointer[0], dy = y - f.pointer[1], dist = Math.hypot(dx, dy), R = 16;
      if (dist < R) {
        const k = (1 - dist / R) * f.presence;
        r *= 1 + 0.75 * k * k;
        // brightened toward white, in steps, so nearby dots still share a batch
        const w = Math.round(0.5 * k * 8) / 8;
        cr += (255 - cr) * w; cg += (255 - cg) * w; cb += (255 - cb) * w;
        const push = (k * k * 3.2) / (dist || 1);
        x += dx * push; y += dy * push;
      }
    }

    if (r <= 0.02 || a <= 0.02) continue;
    const key = `${cr | 0},${cg | 0},${cb | 0}|${Math.round(a * 10)}`;
    let path = batches.get(key);
    if (!path) batches.set(key, (path = new Path2D()));
    path.moveTo(x + r, y);
    path.arc(x, y, r, 0, 6.2832);
  }
  for (const [key, path] of batches) {
    const [rgb, a] = key.split("|");
    ctx.globalAlpha = Number(a) / 10;
    ctx.fillStyle = `rgb(${rgb})`;
    ctx.fill(path);
  }
  ctx.globalAlpha = 1;
}
